AllCops:
  Exclude:
    - '*.gemspec'
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/ClassVars:
  Enabled: false
Metric/ParameterLists:
  Enabled: false
